[versions]
slf4j = "2.0.17"
log4j-slf4j-binding = "2.25.2"

[libraries]
mcp-sdk = "io.modelcontextprotocol.sdk:mcp:0.15.0"

servlet-api = "jakarta.servlet:jakarta.servlet-api:6.1.0"
slf4j-api = {module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
slf4j-runtime-log4j2 = {module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j-slf4j-binding"}